space_usda_path = "../assets/models/input_space/room.usda"
placement_region_usda_path = "../assets/models/input_placement_region/chair0.usda"
regions_type_path = "../config/regions_types.toml"
# meters -> millimeters (or any unit scale you want)
usda_scale = 1.0
