[package]
name = "asset_import"
version = "0.1.0"
edition = "2021"

[dependencies]
geometry_core = { path = "../geometry_core" }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
types = { path = "../types" }
